name: Deploy Blazor PWA to GitHub Pages

on:
  push:
    branches:
      - main  # Samo ob pushu na vejo 'main' bo potekal deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Preveri, da imaš ustrezno verzijo .NET
    - name: Publish
      run: dotnet publish ./BlazorTest.csproj -c Release -o release  # Določitev poti do .csproj
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: release/wwwroot  # To mora biti pot do 'wwwroot' v tvoji objavljeni aplikaciji
